[package]
name = "daw-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
daw-core.workspace = true
daw-media.workspace = true
daw-engine.workspace = true
daw-project.workspace = true
daw-output.workspace = true
egui.workspace = true
egui_extras = { version = "0.36.2", default-features = false, features = ["svg"] }
egui-lucide = "0.1.0"
rfd.workspace = true
